export type DifficultyLevel = 'basit' | 'orta' | 'zor';

export interface PracticeSentence {
  turkish: string;
  english: string;
  level: DifficultyLevel;
}

export const SENTENCES: PracticeSentence[] = [
  // Basit (A1-A2)
  { level: 'basit', turkish: 'Ben her sabah kahve içerim.', english: 'I drink coffee every morning.' },
  { level: 'basit', turkish: 'O elma sever.', english: 'He likes apples.' },
  { level: 'basit', turkish: 'Biz okula gidiyoruz.', english: 'We are going to school.' },
  { level: 'basit', turkish: 'Benim arabam kırmızı.', english: 'My car is red.' },
  { level: 'basit', turkish: 'Onlar parkta oynuyorlar.', english: 'They are playing in the park.' },
  { level: 'basit', turkish: 'Sen çok hızlı koşuyorsun.', english: 'You run very fast.' },
  { level: 'basit', turkish: 'Kedim masanın altında uyuyor.', english: 'My cat is sleeping under the table.' },
  { level: 'basit', turkish: 'Bugün hava çok güzel.', english: 'The weather is very nice today.' },
  { level: 'basit', turkish: 'Ben kitap okumayı severim.', english: 'I like reading books.' },
  { level: 'basit', turkish: 'O her gün süt içer.', english: 'She drinks milk every day.' },
  { level: 'basit', turkish: 'Benim adım Ali.', english: 'My name is Ali.' },
  { level: 'basit', turkish: 'Bizim büyük bir evimiz var.', english: 'We have a big house.' },
  { level: 'basit', turkish: 'Onlar İngilizce konuşabiliyor.', english: 'They can speak English.' },
  { level: 'basit', turkish: 'Sen yorgun görünüyorsun.', english: 'You look tired.' },
  { level: 'basit', turkish: 'Köpek havlıyor.', english: 'The dog is barking.' },
  { level: 'basit', turkish: 'Ben müzik dinliyorum.', english: 'I am listening to music.' },
  { level: 'basit', turkish: 'O bana yardım etti.', english: 'He helped me.' },
  { level: 'basit', turkish: 'Biz dün sinemaya gittik.', english: 'We went to the cinema yesterday.' },
  { level: 'basit', turkish: 'Onlar yarın gelecekler.', english: 'They will come tomorrow.' },
  { level: 'basit', turkish: 'Sen ne yapıyorsun?', english: 'What are you doing?' },
  { level: 'basit', turkish: 'Benim iki kardeşim var.', english: 'I have two siblings.' },
  { level: 'basit', turkish: 'O çok güzel şarkı söyler.', english: 'She sings very beautifully.' },
  { level: 'basit', turkish: 'Biz tatilde Antalya\'ya gideceğiz.', english: 'We will go to Antalya on holiday.' },
  { level: 'basit', turkish: 'Onlar futbol oynamayı seviyor.', english: 'They like playing football.' },
  { level: 'basit', turkish: 'Sen nerede yaşıyorsun?', english: 'Where do you live?' },
  { level: 'basit', turkish: 'Ben kahvaltı yapıyorum.', english: 'I am having breakfast.' },
  { level: 'basit', turkish: 'O her sabah erken kalkar.', english: 'He gets up early every morning.' },
  { level: 'basit', turkish: 'Biz akşam yemeği yiyoruz.', english: 'We are having dinner.' },
  { level: 'basit', turkish: 'Onlar televizyon izliyorlar.', english: 'They are watching television.' },
  { level: 'basit', turkish: 'Sen çok çalışkansın.', english: 'You are very hardworking.' },

  // Orta (A2-B1)
  { level: 'orta', turkish: 'Çok işim var ama zamanım az, istediklerimi bir an önce yapmalıyım.', english: 'I have a lot of work but little time, I must do what I want as soon as possible.' },
  { level: 'orta', turkish: 'Hava yağmurlu olduğu için dışarı çıkmak istemiyorum.', english: 'I don\'t want to go out because the weather is rainy.' },
  { level: 'orta', turkish: 'Eğer erken kalkarsan, otobüsü yakalayabilirsin.', english: 'If you get up early, you can catch the bus.' },
  { level: 'orta', turkish: 'Dün akşam izlediğim film gerçekten çok sıkıcıydı.', english: 'The movie I watched last night was really boring.' },
  { level: 'orta', turkish: 'Yeni bir dil öğrenmek zaman alır ama çok faydalıdır.', english: 'Learning a new language takes time but it is very useful.' },
  { level: 'orta', turkish: 'Arkadaşlarımla buluşmadan önce ödevlerimi bitirmem gerekiyor.', english: 'I need to finish my homework before meeting my friends.' },
  { level: 'orta', turkish: 'Geçen yaz gittiğimiz tatil hayatımın en iyi tatiliydi.', english: 'The holiday we went on last summer was the best holiday of my life.' },
  { level: 'orta', turkish: 'Ne kadar çok pratik yaparsan, o kadar hızlı öğrenirsin.', english: 'The more you practice, the faster you learn.' },
  { level: 'orta', turkish: 'Bu kitabı okumayı bitirdiğimde sana ödünç verebilirim.', english: 'When I finish reading this book, I can lend it to you.' },
  { level: 'orta', turkish: 'Sağlıklı kalmak için düzenli olarak spor yapmalısın.', english: 'You should exercise regularly to stay healthy.' },
  { level: 'orta', turkish: 'O kadar yorgundum ki eve gelir gelmez uyuyakaldım.', english: 'I was so tired that I fell asleep as soon as I got home.' },
  { level: 'orta', turkish: 'Sınavdan yüksek not almak istiyorsan daha çok çalışmalısın.', english: 'If you want to get a high mark in the exam, you should study harder.' },
  { level: 'orta', turkish: 'Dışarı çıkarken yanına şemsiye almayı unutma, yağmur yağabilir.', english: 'Don\'t forget to take an umbrella with you when going out, it might rain.' },
  { level: 'orta', turkish: 'Yeni işime başlamak için sabırsızlanıyorum.', english: 'I am looking forward to starting my new job.' },
  { level: 'orta', turkish: 'Hafta sonu ne yapacağımıza henüz karar vermedik.', english: 'We haven\'t decided what to do at the weekend yet.' },
  { level: 'orta', turkish: 'O kadar hızlı konuştu ki ne dediğini anlayamadım.', english: 'He spoke so fast that I couldn\'t understand what he said.' },
  { level: 'orta', turkish: 'Bilgisayarım bozulduğu için projemi zamanında bitiremedim.', english: 'I couldn\'t finish my project on time because my computer broke down.' },
  { level: 'orta', turkish: 'Eğer bana ihtiyacın olursa, beni her zaman arayabilirsin.', english: 'If you need me, you can always call me.' },
  { level: 'orta', turkish: 'Bu restoranın yemekleri çok lezzetli ama fiyatları biraz pahalı.', english: 'The food at this restaurant is very delicious but the prices are a bit expensive.' },
  { level: 'orta', turkish: 'İngilizce konuşma pratiği yapmak için yabancı arkadaşlar ediniyorum.', english: 'I am making foreign friends to practice speaking English.' },
  { level: 'orta', turkish: 'Toplantı saat ikide başlayacak, lütfen geç kalmayın.', english: 'The meeting will start at two o\'clock, please don\'t be late.' },
  { level: 'orta', turkish: 'Dün gece çok geç uyuduğum için bugün kendimi yorgun hissediyorum.', english: 'I feel tired today because I slept very late last night.' },
  { level: 'orta', turkish: 'Yeni taşındığımız ev eskisinden çok daha büyük ve aydınlık.', english: 'The house we just moved into is much bigger and brighter than the old one.' },
  { level: 'orta', turkish: 'Eğer paranı biriktirirsen, istediğin o arabayı alabilirsin.', english: 'If you save your money, you can buy that car you want.' },
  { level: 'orta', turkish: 'Bu sorunu çözmek için hep birlikte çalışmalıyız.', english: 'We must work together to solve this problem.' },
  { level: 'orta', turkish: 'Konser biletleri çok çabuk tükendiği için gidemedik.', english: 'We couldn\'t go to the concert because the tickets sold out very quickly.' },
  { level: 'orta', turkish: 'Her gün en az yarım saat kitap okumaya çalışıyorum.', english: 'I try to read a book for at least half an hour every day.' },
  { level: 'orta', turkish: 'Yeni tarifler denemeyi ve mutfakta vakit geçirmeyi seviyorum.', english: 'I like trying new recipes and spending time in the kitchen.' },
  { level: 'orta', turkish: 'Eğer hava güzel olursa hafta sonu pikniğe gideceğiz.', english: 'If the weather is nice, we will go for a picnic at the weekend.' },
  { level: 'orta', turkish: 'Bu kadar çok çalıştıktan sonra güzel bir tatili hak ettin.', english: 'You deserve a nice holiday after working so hard.' },

  // Zor (B2-C1)
  { level: 'zor', turkish: 'Eğer dün bana haber verseydin, planlarımı iptal edip sana yardım etmeye gelebilirdim.', english: 'If you had let me know yesterday, I could have cancelled my plans and come to help you.' },
  { level: 'zor', turkish: 'Ne kadar çok çalışırsan çalış, bazen şansın da yaver gitmesi gerekir.', english: 'No matter how hard you work, sometimes you also need a bit of luck.' },
  { level: 'zor', turkish: 'Teknolojinin hızla gelişmesi, günlük hayatımızı tahmin edemeyeceğimiz şekillerde değiştirdi.', english: 'The rapid development of technology has changed our daily lives in ways we could not have imagined.' },
  { level: 'zor', turkish: 'Bu projenin başarılı olması için sadece çok çalışmak yetmez, aynı zamanda yenilikçi fikirler de üretmeliyiz.', english: 'For this project to be successful, working hard is not enough; we must also generate innovative ideas.' },
  { level: 'zor', turkish: 'Toplumun çevre bilinci konusunda daha fazla eğitilmesi gerektiğine inanıyorum.', english: 'I believe that society needs to be educated more about environmental awareness.' },
  { level: 'zor', turkish: 'Küresel ısınmanın etkilerini azaltmak için acilen uluslararası düzeyde önlemler alınmalıdır.', english: 'Measures must be taken urgently at the international level to reduce the effects of global warming.' },
  { level: 'zor', turkish: 'Her ne kadar farklı görüşlere sahip olsak da, ortak bir amaç uğruna birlikte çalışabilmeliyiz.', english: 'Even though we have different opinions, we should be able to work together for a common goal.' },
  { level: 'zor', turkish: 'Çocukların erken yaşta yabancı dil öğrenmeye başlaması, onların bilişsel gelişimini olumlu yönde etkiler.', english: 'Children starting to learn a foreign language at an early age positively affects their cognitive development.' },
  { level: 'zor', turkish: 'Ekonomik krizin üstesinden gelmek için hükümetin daha köklü reformlar yapması şarttır.', english: 'It is essential for the government to make more fundamental reforms to overcome the economic crisis.' },
  { level: 'zor', turkish: 'Sanatın toplum üzerindeki iyileştirici gücü, tarih boyunca pek çok kez kanıtlanmıştır.', english: 'The healing power of art on society has been proven many times throughout history.' },
  { level: 'zor', turkish: 'Uzaktan çalışmanın yaygınlaşması, hem çalışanlar hem de işverenler için yeni fırsatlar ve zorluklar yarattı.', english: 'The widespread adoption of remote work has created new opportunities and challenges for both employees and employers.' },
  { level: 'zor', turkish: 'Bir insanın karakteri, zor zamanlarda aldığı kararlarla ve gösterdiği tutumla belli olur.', english: 'A person\'s character is revealed by the decisions they make and the attitude they show in difficult times.' },
  { level: 'zor', turkish: 'Geçmişte yapılan hatalardan ders çıkarmak, gelecekte daha doğru adımlar atmamızı sağlar.', english: 'Learning from mistakes made in the past allows us to take more accurate steps in the future.' },
  { level: 'zor', turkish: 'Sosyal medyanın gençler üzerindeki olumsuz etkilerini en aza indirmek için ebeveynlere büyük görevler düşüyor.', english: 'Parents have great responsibilities to minimize the negative effects of social media on young people.' },
  { level: 'zor', turkish: 'Başarının sırrı, asla pes etmemek ve karşılaşılan engelleri birer öğrenme fırsatı olarak görmektir.', english: 'The secret to success is never giving up and seeing the obstacles encountered as learning opportunities.' },
  { level: 'zor', turkish: 'İklim değişikliğiyle mücadele, sadece devletlerin değil, her bireyin sorumluluk almasını gerektiren küresel bir sorundur.', english: 'Combating climate change is a global problem that requires not only governments but every individual to take responsibility.' },
  { level: 'zor', turkish: 'Yapay zeka teknolojilerinin gelişimi, gelecekte birçok mesleğin yok olmasına veya tamamen değişmesine neden olabilir.', english: 'The development of artificial intelligence technologies may cause many professions to disappear or change completely in the future.' },
  { level: 'zor', turkish: 'Farklı kültürleri tanımak ve anlamak, önyargıları yıkmanın ve daha hoşgörülü bir toplum inşa etmenin en etkili yoludur.', english: 'Getting to know and understanding different cultures is the most effective way to break down prejudices and build a more tolerant society.' },
  { level: 'zor', turkish: 'Sağlıklı bir yaşam sürdürmek için sadece fiziksel aktivite değil, aynı zamanda ruh sağlığına da dikkat etmek gerekir.', english: 'To maintain a healthy life, it is necessary to pay attention not only to physical activity but also to mental health.' },
  { level: 'zor', turkish: 'Eğitim sisteminin ezbere dayalı olmaktan çıkıp, eleştirel düşünmeyi ve yaratıcılığı teşvik eden bir yapıya kavuşması elzemdir.', english: 'It is essential that the education system moves away from being rote-based and gains a structure that encourages critical thinking and creativity.' },
  { level: 'zor', turkish: 'Şirketlerin sürdürülebilirlik politikalarını benimsemesi, hem çevreye duyarlılık hem de uzun vadeli karlılık açısından önemlidir.', english: 'Companies adopting sustainability policies is important in terms of both environmental awareness and long-term profitability.' },
  { level: 'zor', turkish: 'Gelişmekte olan ülkelerin ekonomik kalkınmasını hızlandırmak için altyapı yatırımlarına daha fazla önem verilmelidir.', english: 'More importance should be given to infrastructure investments to accelerate the economic development of developing countries.' },
  { level: 'zor', turkish: 'İnsan hakları ihlallerinin önlenmesi ve adaletin sağlanması, demokratik bir toplumun en temel yapı taşlarıdır.', english: 'The prevention of human rights violations and the provision of justice are the most fundamental building blocks of a democratic society.' },
  { level: 'zor', turkish: 'Uzay araştırmalarına ayrılan bütçenin artırılması, evrenin sırlarını çözmemize ve yeni teknolojiler geliştirmemize olanak tanıyacaktır.', english: 'Increasing the budget allocated to space research will allow us to unravel the secrets of the universe and develop new technologies.' },
  { level: 'zor', turkish: 'Geleneksel medyanın yerini giderek dijital platformlara bırakması, haber alma alışkanlıklarımızı köklü bir şekilde değiştirdi.', english: 'Traditional media increasingly giving way to digital platforms has radically changed our news consumption habits.' },
  { level: 'zor', turkish: 'Bir ülkenin gelişmişlik düzeyi, sadece ekonomik göstergelerle değil, aynı zamanda eğitim ve sağlık hizmetlerinin kalitesiyle de ölçülür.', english: 'A country\'s level of development is measured not only by economic indicators but also by the quality of education and health services.' },
  { level: 'zor', turkish: 'Tüketim çılgınlığının önüne geçmek ve daha minimalist bir yaşam tarzı benimsemek, hem bireysel mutluluk hem de gezegenin geleceği için gereklidir.', english: 'Preventing the consumption frenzy and adopting a more minimalist lifestyle is necessary for both individual happiness and the future of the planet.' },
  { level: 'zor', turkish: 'Farklı kuşaklar arasındaki iletişim kopukluğunu gidermek için karşılıklı anlayış ve empatiye dayalı bir diyalog ortamı oluşturulmalıdır.', english: 'To bridge the communication gap between different generations, a dialogue environment based on mutual understanding and empathy should be created.' },
  { level: 'zor', turkish: 'Sanat ve kültür etkinliklerine katılımın teşvik edilmesi, toplumun estetik algısını geliştirir ve yaşam kalitesini artırır.', english: 'Encouraging participation in art and cultural events develops the aesthetic perception of society and increases the quality of life.' },
  { level: 'zor', turkish: 'Küreselleşmenin getirdiği fırsatlardan eşit bir şekilde yararlanabilmek için eğitimde fırsat eşitliğinin sağlanması büyük önem taşımaktadır.', english: 'In order to benefit equally from the opportunities brought by globalization, ensuring equal opportunities in education is of great importance.' },
];
